[package]
name = "sentinel_ai"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
sentinel_ai = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "devnet" }
